-- ====================================================================
-- SUPABASE DATABASE SETUP SCHEMA
-- For Harendra Lamsal's CMS Blog & Category Tables
-- ====================================================================

-- 1. Create the Blog Categories Table
CREATE TABLE IF NOT EXISTS blog_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name_en TEXT NOT NULL,
    name_ne TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the Blog Posts Table
CREATE TABLE IF NOT EXISTS blog_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT NOT NULL UNIQUE,
    title_en TEXT NOT NULL,
    title_ne TEXT,
    excerpt_en TEXT,
    excerpt_ne TEXT,
    body_en TEXT NOT NULL,
    body_ne TEXT,
    cover_image_url TEXT,
    category_id BIGINT REFERENCES blog_categories(id) ON DELETE SET NULL,
    tags TEXT[] DEFAULT '{}'::text[],
    lang TEXT DEFAULT 'en',
    reading_minutes INTEGER DEFAULT 5,
    seo_title TEXT,
    seo_description TEXT,
    published BOOLEAN DEFAULT TRUE,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    views_count INTEGER DEFAULT 0,
    focus_keyword TEXT,
    secondary_keywords TEXT[] DEFAULT '{}'::text[],
    internal_link_suggestions TEXT[] DEFAULT '{}'::text[],
    external_references TEXT[] DEFAULT '{}'::text[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create helpful indexes for ultra-fast query performance
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_categories_slug ON blog_categories(slug);

-- 4. Set up default Row Level Security (RLS) policies
-- This allows anyone to read/view blog posts & categories, 
-- and allows your server backend API (using Anon Key or Service Role) to insert/modify items.
ALTER TABLE blog_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- Category Policies
CREATE POLICY "Allow public read access to categories" 
ON blog_categories FOR SELECT 
TO public 
USING (true);

CREATE POLICY "Allow authenticated service insertion to categories" 
ON blog_categories FOR ALL 
TO anon, authenticated, service_role 
USING (true) 
WITH CHECK (true);

-- Post Policies
CREATE POLICY "Allow public read access to posts" 
ON blog_posts FOR SELECT 
TO public 
USING (published = true);

CREATE POLICY "Allow authenticated service insertion to posts" 
ON blog_posts FOR ALL 
TO anon, authenticated, service_role 
USING (true) 
WITH CHECK (true);

-- 5. Insert initial default categories so your CMS is ready to use
INSERT INTO blog_categories (slug, name_en, name_ne) VALUES
('web-development', 'Web Development', 'वेब विकास'),
('artificial-intelligence', 'Artificial Intelligence', 'कृत्रिम बुद्धिमत्ता'),
('cyber-security', 'Cyber Security', 'साइबर सुरक्षा'),
('digital-marketing', 'Digital Marketing', 'डिजिटल मार्केटिङ'),
('programming', 'Programming', 'प्रोग्रामिङ')
ON CONFLICT (slug) DO NOTHING;
